/**
 * The treks themselves — route, itinerary, physical demand.
 *
 * Split from `departures.ts` because two Everest dates walk the same route. If
 * the itinerary lived on the departure it would be copied once per date and the
 * copies would drift, which is exactly the class of error this section exists to
 * avoid. A departure carries only what genuinely differs between dates: when it
 * goes, who has booked, what it costs, and the photograph.
 *
 * THE ITINERARY RULES.
 *
 *   1. `sleepAltitudeM` is mandatory on every day, and it is the SLEEPING
 *      altitude. Altitude illness is a function of where the night is spent,
 *      not of the day's high point — an itinerary that advertises its peak and
 *      hides where it sleeps is hiding the number that matters.
 *   2. `maxAltitudeM` is set only when the day tops out above where it sleeps.
 *      That gap is the whole point of an acclimatisation day, so it is stated.
 *   3. Acclimatisation days carry `isAcclimatisation`. They are never folded
 *      into a normal day — a rest day the reader cannot find is a rest day they
 *      cannot count.
 *   4. Travel days carry `isTravelDay`. The Lukla flight and the Besisahar
 *      jeep are transport, and padding a day count with them is how a nine-day
 *      trek gets sold as twelve.
 */

export type ItineraryDay = {
  day: number;
  title: string;
  fromPlace?: string;
  toPlace: string;
  /** Where the night is spent. Never omitted, never the day's peak. */
  sleepAltitudeM: number;
  /** Only when the day goes higher than it sleeps. */
  maxAltitudeM?: number;
  walkingHours?: string;
  distanceKm?: number;
  accommodation: "teahouse" | "lodge" | "hotel" | "camp";
  meals: ("breakfast" | "lunch" | "dinner")[];
  note?: string;
  /** Rest and acclimatisation. Marked, never hidden inside a normal day. */
  isAcclimatisation?: boolean;
  /** Flights and drives. Marked, never dressed up as a day of walking. */
  isTravelDay?: boolean;
};

export type PhysicalDemand = {
  /** Hours on trail on a typical day, e.g. "5–7". */
  walkingHoursPerDay: string;
  /** How many days in a row that happens. */
  consecutiveDays: number;
  terrain: string;
  /** What to be able to do before arriving. Describes the trek, not the reader. */
  preparationNote: string;
};

export type TrekProfile = {
  trekName: string;
  region: string;
  difficulty: "moderate" | "challenging" | "strenuous";
  /** The highest point reached on a walking day. Travel days do not count. */
  maxAltitudeM: number;
  guideRatio: string;
  /** Altitude above which a second guide joins the group. */
  assistantGuideAbove?: number;
  groupSizeMax: number;
  /** Two sentences. Factual — the banned adjective list applies here too. */
  summary: string;
  physicalDemand: PhysicalDemand;
  itinerary: ItineraryDay[];
};

/** Where an itinerary is allowed to end. The guard checks the last day. */
export const RETURN_POINTS = ["Kathmandu", "Pokhara"] as const;

const BLD: ItineraryDay["meals"] = ["breakfast", "lunch", "dinner"];

export const TREKS: Record<string, TrekProfile> = {
  "everest-base-camp": {
    trekName: "Everest Base Camp",
    region: "Khumbu",
    difficulty: "challenging",
    maxAltitudeM: 5364,
    guideRatio: "1:4",
    assistantGuideAbove: 4000,
    groupSizeMax: 12,
    summary:
      "Twelve days from Lukla to Everest Base Camp and back, sleeping in teahouses the whole way. Two of those days are spent without gaining altitude, which is what the rest of the schedule is built around.",
    physicalDemand: {
      walkingHoursPerDay: "5–7",
      consecutiveDays: 9,
      terrain:
        "Stone staircases, suspension bridges and glacial moraine. No technical ground and no ropes; the difficulty is the altitude and the repetition.",
      preparationNote:
        "Nine days of walking in a row, most of them five to seven hours with a daypack. Walking a hilly 15 km day and getting up to do it again the next morning is the shape of it.",
    },
    itinerary: [
      {
        day: 1,
        title: "Arrive in Kathmandu",
        toPlace: "Kathmandu",
        sleepAltitudeM: 1400,
        accommodation: "hotel",
        meals: ["dinner"],
        isTravelDay: true,
        note: "Kit check and briefing at 17:00. Your guide goes through the route, the acclimatisation days and the turnaround rules before anyone flies.",
      },
      {
        day: 2,
        title: "Fly to Lukla, walk to Phakding",
        fromPlace: "Kathmandu",
        toPlace: "Phakding",
        sleepAltitudeM: 2610,
        maxAltitudeM: 2840,
        walkingHours: "3",
        distanceKm: 6.2,
        accommodation: "teahouse",
        meals: BLD,
        isTravelDay: true,
        note: "From mid-March to May and from October to November this flight leaves from Ramechhap, not Kathmandu. That means a four-to-five hour drive starting around 1am, which we provide and which is priced in the cost sheet. The flight is weather-dependent and can move by a day; the cost of that delay sits with us.",
      },
      {
        day: 3,
        title: "Phakding to Namche Bazaar",
        fromPlace: "Phakding",
        toPlace: "Namche Bazaar",
        sleepAltitudeM: 3440,
        walkingHours: "6",
        distanceKm: 10.5,
        accommodation: "teahouse",
        meals: BLD,
        note: "The climb from the Dudh Koshi to Namche is the first long day. It is walked slowly on purpose.",
      },
      {
        day: 4,
        title: "Namche acclimatisation day",
        toPlace: "Namche Bazaar",
        sleepAltitudeM: 3440,
        maxAltitudeM: 3880,
        walkingHours: "3",
        accommodation: "teahouse",
        meals: BLD,
        isAcclimatisation: true,
        note: "Up toward the Everest View ridge and back down to the same bed. Climb high, sleep low.",
      },
      {
        day: 5,
        title: "Namche to Tengboche",
        fromPlace: "Namche Bazaar",
        toPlace: "Tengboche",
        sleepAltitudeM: 3860,
        walkingHours: "5",
        distanceKm: 9.2,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 6,
        title: "Tengboche to Dingboche",
        fromPlace: "Tengboche",
        toPlace: "Dingboche",
        sleepAltitudeM: 4410,
        walkingHours: "5",
        distanceKm: 11,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 7,
        title: "Dingboche acclimatisation day",
        toPlace: "Dingboche",
        sleepAltitudeM: 4410,
        maxAltitudeM: 4900,
        walkingHours: "4",
        accommodation: "teahouse",
        meals: BLD,
        isAcclimatisation: true,
        note: "Up the Nangkartshang ridge and back. The second scheduled day with no net gain.",
      },
      {
        day: 8,
        title: "Dingboche to Lobuche",
        fromPlace: "Dingboche",
        toPlace: "Lobuche",
        sleepAltitudeM: 4940,
        walkingHours: "5",
        distanceKm: 8.5,
        accommodation: "teahouse",
        meals: BLD,
        note: "Past the memorials above Thukla Pass.",
      },
      {
        day: 9,
        title: "Lobuche to Everest Base Camp, sleep at Gorak Shep",
        fromPlace: "Lobuche",
        toPlace: "Gorak Shep",
        sleepAltitudeM: 5164,
        maxAltitudeM: 5364,
        walkingHours: "7",
        distanceKm: 13,
        accommodation: "teahouse",
        meals: BLD,
        note: "The high point of the trek at 5,364 m and the highest night at 5,164 m.",
      },
      {
        day: 10,
        title: "Gorak Shep to Pheriche",
        fromPlace: "Gorak Shep",
        toPlace: "Pheriche",
        sleepAltitudeM: 4371,
        walkingHours: "6",
        distanceKm: 15,
        accommodation: "teahouse",
        meals: BLD,
        note: "A descent of nearly 800 m. Most people sleep properly for the first time in three nights.",
      },
      {
        day: 11,
        title: "Pheriche to Namche Bazaar",
        fromPlace: "Pheriche",
        toPlace: "Namche Bazaar",
        sleepAltitudeM: 3440,
        walkingHours: "7",
        distanceKm: 20,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 12,
        title: "Namche to Lukla, fly to Kathmandu",
        fromPlace: "Namche Bazaar",
        toPlace: "Kathmandu",
        sleepAltitudeM: 1400,
        walkingHours: "6",
        accommodation: "hotel",
        meals: ["breakfast", "lunch"],
        isTravelDay: true,
      },
    ],
  },

  "annapurna-base-camp": {
    trekName: "Annapurna Base Camp",
    region: "Annapurna",
    difficulty: "moderate",
    maxAltitudeM: 4130,
    guideRatio: "1:4",
    groupSizeMax: 10,
    summary:
      "Nine days into the Annapurna sanctuary and out through Jhinu Danda. No separate acclimatisation day is scheduled, because the profile gains under 450 m a night above 3,000 m and the last day up is a two-hour one.",
    physicalDemand: {
      walkingHoursPerDay: "5–6",
      consecutiveDays: 7,
      terrain:
        "Stone steps, rhododendron forest and a glacial basin. Steep in places, particularly the descent past Bamboo, but never exposed.",
      preparationNote:
        "Seven walking days of five to six hours, with a great deal of stair climbing. Regular hill walking in the months beforehand is the preparation that carries.",
    },
    itinerary: [
      {
        day: 1,
        title: "Kathmandu to Pokhara",
        fromPlace: "Kathmandu",
        toPlace: "Pokhara",
        sleepAltitudeM: 822,
        accommodation: "hotel",
        meals: ["dinner"],
        isTravelDay: true,
        note: "Tourist coach or a 25-minute flight. Both are in the price and the choice is yours.",
      },
      {
        day: 2,
        title: "Pokhara to Ghandruk",
        fromPlace: "Pokhara",
        toPlace: "Ghandruk",
        sleepAltitudeM: 1940,
        walkingHours: "5",
        distanceKm: 9,
        accommodation: "teahouse",
        meals: BLD,
        note: "Drive to Nayapul, then a steady climb into the first Gurung village.",
      },
      {
        day: 3,
        title: "Ghandruk to Chhomrong",
        fromPlace: "Ghandruk",
        toPlace: "Chhomrong",
        sleepAltitudeM: 2170,
        walkingHours: "5",
        distanceKm: 10,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 4,
        title: "Chhomrong to Dovan",
        fromPlace: "Chhomrong",
        toPlace: "Dovan",
        sleepAltitudeM: 2600,
        walkingHours: "6",
        distanceKm: 12,
        accommodation: "teahouse",
        meals: BLD,
        note: "Down the long stone staircase to the Chhomrong Khola and back up the far side.",
      },
      {
        day: 5,
        title: "Dovan to Machhapuchhre Base Camp",
        fromPlace: "Dovan",
        toPlace: "Machhapuchhre Base Camp",
        sleepAltitudeM: 3700,
        walkingHours: "6",
        distanceKm: 11,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 6,
        title: "Machhapuchhre to Annapurna Base Camp",
        fromPlace: "Machhapuchhre Base Camp",
        toPlace: "Annapurna Base Camp",
        sleepAltitudeM: 4130,
        walkingHours: "2",
        distanceKm: 4,
        accommodation: "teahouse",
        meals: BLD,
        note: "A short day by design: 430 m of gain, then the afternoon spent resting at the highest night of the trek.",
      },
      {
        day: 7,
        title: "Annapurna Base Camp to Bamboo",
        fromPlace: "Annapurna Base Camp",
        toPlace: "Bamboo",
        sleepAltitudeM: 2310,
        walkingHours: "7",
        distanceKm: 16,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 8,
        title: "Bamboo to Jhinu Danda",
        fromPlace: "Bamboo",
        toPlace: "Jhinu Danda",
        sleepAltitudeM: 1780,
        walkingHours: "5",
        distanceKm: 11,
        accommodation: "teahouse",
        meals: BLD,
        note: "The hot springs are twenty minutes below the village.",
      },
      {
        day: 9,
        title: "Jhinu Danda to Pokhara",
        fromPlace: "Jhinu Danda",
        toPlace: "Pokhara",
        sleepAltitudeM: 822,
        walkingHours: "2",
        accommodation: "hotel",
        meals: ["breakfast", "lunch"],
        isTravelDay: true,
      },
    ],
  },

  "annapurna-circuit": {
    trekName: "Annapurna Circuit",
    region: "Annapurna",
    difficulty: "strenuous",
    maxAltitudeM: 5416,
    guideRatio: "1:4",
    assistantGuideAbove: 4500,
    groupSizeMax: 12,
    summary:
      "Fourteen days around the Annapurna massif, crossing Thorong La at 5,416 m on day eight. A full acclimatisation day at Manang sits before the pass, and the schedule holds a spare day so a closed crossing does not have to be rushed.",
    physicalDemand: {
      walkingHoursPerDay: "5–8",
      consecutiveDays: 11,
      terrain:
        "Jeep track, river gorge, high desert and one long pass day on scree. The pass starts before dawn and runs eight to ten hours.",
      preparationNote:
        "Eleven walking days, with 1,000 m of ascent and 1,600 m of descent inside the pass day alone. Long back-to-back hill days with a loaded pack are the closest equivalent at home.",
    },
    itinerary: [
      {
        day: 1,
        title: "Kathmandu to Besisahar",
        fromPlace: "Kathmandu",
        toPlace: "Besisahar",
        sleepAltitudeM: 760,
        accommodation: "lodge",
        meals: ["dinner"],
        isTravelDay: true,
      },
      {
        day: 2,
        title: "Besisahar to Chame",
        fromPlace: "Besisahar",
        toPlace: "Chame",
        sleepAltitudeM: 2670,
        accommodation: "teahouse",
        meals: BLD,
        isTravelDay: true,
        note: "Jeep on the rough upper road. That road is why this itinerary is fourteen days rather than twenty-one.",
      },
      {
        day: 3,
        title: "Chame to Pisang",
        fromPlace: "Chame",
        toPlace: "Pisang",
        sleepAltitudeM: 3300,
        walkingHours: "6",
        distanceKm: 15,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 4,
        title: "Pisang to Manang",
        fromPlace: "Pisang",
        toPlace: "Manang",
        sleepAltitudeM: 3519,
        walkingHours: "6",
        distanceKm: 17,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 5,
        title: "Manang acclimatisation day",
        toPlace: "Manang",
        sleepAltitudeM: 3519,
        maxAltitudeM: 4000,
        walkingHours: "4",
        accommodation: "teahouse",
        meals: BLD,
        isAcclimatisation: true,
        note: "Up toward Praken Gompa and back down to the same bed.",
      },
      {
        day: 6,
        title: "Manang to Yak Kharka",
        fromPlace: "Manang",
        toPlace: "Yak Kharka",
        sleepAltitudeM: 4050,
        walkingHours: "4",
        distanceKm: 10,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 7,
        title: "Yak Kharka to Thorong Phedi",
        fromPlace: "Yak Kharka",
        toPlace: "Thorong Phedi",
        sleepAltitudeM: 4525,
        walkingHours: "4",
        distanceKm: 7,
        accommodation: "teahouse",
        meals: BLD,
        note: "A short day on purpose. The pass starts at 04:00.",
      },
      {
        day: 8,
        title: "Thorong La to Muktinath",
        fromPlace: "Thorong Phedi",
        toPlace: "Muktinath",
        sleepAltitudeM: 3760,
        maxAltitudeM: 5416,
        walkingHours: "8–10",
        distanceKm: 16,
        accommodation: "teahouse",
        meals: BLD,
        note: "The high point of the trek. If the pass is closed we wait at Phedi rather than cross it; the spare day exists for this.",
      },
      {
        day: 9,
        title: "Muktinath to Marpha",
        fromPlace: "Muktinath",
        toPlace: "Marpha",
        sleepAltitudeM: 2670,
        walkingHours: "5",
        distanceKm: 14,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 10,
        title: "Marpha to Tatopani",
        fromPlace: "Marpha",
        toPlace: "Tatopani",
        sleepAltitudeM: 1200,
        accommodation: "teahouse",
        meals: BLD,
        isTravelDay: true,
        note: "Jeep down the Kali Gandaki. The hot springs are beside the lodge.",
      },
      {
        day: 11,
        title: "Tatopani to Ghorepani",
        fromPlace: "Tatopani",
        toPlace: "Ghorepani",
        sleepAltitudeM: 2874,
        walkingHours: "7",
        distanceKm: 16,
        accommodation: "teahouse",
        meals: BLD,
        note: "1,674 m of ascent, and the hardest climb of the trek after the pass itself.",
      },
      {
        day: 12,
        title: "Poon Hill, then Tadapani",
        fromPlace: "Ghorepani",
        toPlace: "Tadapani",
        sleepAltitudeM: 2630,
        maxAltitudeM: 3210,
        walkingHours: "6",
        distanceKm: 12,
        accommodation: "teahouse",
        meals: BLD,
        note: "Dawn on Poon Hill, then down through rhododendron forest.",
      },
      {
        day: 13,
        title: "Tadapani to Pokhara",
        fromPlace: "Tadapani",
        toPlace: "Pokhara",
        sleepAltitudeM: 822,
        walkingHours: "4",
        accommodation: "hotel",
        meals: BLD,
        isTravelDay: true,
      },
      {
        day: 14,
        title: "Pokhara to Kathmandu",
        fromPlace: "Pokhara",
        toPlace: "Kathmandu",
        sleepAltitudeM: 1400,
        accommodation: "hotel",
        meals: ["breakfast"],
        isTravelDay: true,
      },
    ],
  },

  "langtang-valley": {
    trekName: "Langtang Valley",
    region: "Langtang",
    difficulty: "moderate",
    maxAltitudeM: 4984,
    guideRatio: "1:4",
    groupSizeMax: 10,
    summary:
      "Seven days up the Langtang valley to Kyanjin Gompa, with one acclimatisation day used for the climb to Tserko Ri at 4,984 m. The valley was rebuilt after the 2015 earthquake and the lodges are owned by the families who returned.",
    physicalDemand: {
      walkingHoursPerDay: "5–6",
      consecutiveDays: 5,
      terrain:
        "Forest trail beside the Langtang Khola, then open yak pasture. One steep optional ridge on the acclimatisation day.",
      preparationNote:
        "Five walking days, with the Tserko Ri climb adding 1,100 m of ascent and descent in a single morning for anyone who takes it. That day is optional and the group splits.",
    },
    itinerary: [
      {
        day: 1,
        title: "Kathmandu to Syabrubesi",
        fromPlace: "Kathmandu",
        toPlace: "Syabrubesi",
        sleepAltitudeM: 1550,
        accommodation: "teahouse",
        meals: ["dinner"],
        isTravelDay: true,
        note: "Seven hours by road along the Trishuli. It is a long drive and we do not pretend otherwise.",
      },
      {
        day: 2,
        title: "Syabrubesi to Lama Hotel",
        fromPlace: "Syabrubesi",
        toPlace: "Lama Hotel",
        sleepAltitudeM: 2470,
        walkingHours: "6",
        distanceKm: 11,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 3,
        title: "Lama Hotel to Langtang village",
        fromPlace: "Lama Hotel",
        toPlace: "Langtang village",
        sleepAltitudeM: 3430,
        walkingHours: "6",
        distanceKm: 14,
        accommodation: "teahouse",
        meals: BLD,
        note: "The trail passes the memorial to the village lost in the 2015 landslide.",
      },
      {
        day: 4,
        title: "Langtang to Kyanjin Gompa",
        fromPlace: "Langtang village",
        toPlace: "Kyanjin Gompa",
        sleepAltitudeM: 3870,
        walkingHours: "3",
        distanceKm: 7,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 5,
        title: "Kyanjin acclimatisation day",
        toPlace: "Kyanjin Gompa",
        sleepAltitudeM: 3870,
        maxAltitudeM: 4984,
        walkingHours: "6",
        accommodation: "teahouse",
        meals: BLD,
        isAcclimatisation: true,
        note: "Tserko Ri and back to the same bed, or a shorter walk to the glacier viewpoint. The high point of the trek either way is reached and given up the same day.",
      },
      {
        day: 6,
        title: "Kyanjin Gompa to Lama Hotel",
        fromPlace: "Kyanjin Gompa",
        toPlace: "Lama Hotel",
        sleepAltitudeM: 2470,
        walkingHours: "6",
        distanceKm: 21,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 7,
        title: "Lama Hotel to Kathmandu",
        fromPlace: "Lama Hotel",
        toPlace: "Kathmandu",
        sleepAltitudeM: 1400,
        walkingHours: "4",
        accommodation: "hotel",
        meals: ["breakfast", "lunch"],
        isTravelDay: true,
      },
    ],
  },

  "upper-mustang": {
    trekName: "Upper Mustang",
    region: "Mustang",
    difficulty: "moderate",
    maxAltitudeM: 3840,
    guideRatio: "1:4",
    groupSizeMax: 8,
    summary:
      "Thirteen days into the restricted area behind the Annapurnas, ending at the walled town of Lo Manthang. It sits in the rain shadow, so it is one of the few routes that works through the monsoon months.",
    physicalDemand: {
      walkingHoursPerDay: "5–7",
      consecutiveDays: 9,
      terrain:
        "High desert — dry canyons, exposed ridgelines and long ascents on loose ground. Wind through the middle of the day is a constant.",
      preparationNote:
        "Nine walking days at altitude with little shade and repeated 400 m climbs. The trek is not steep by Nepali standards; it is long, dry and exposed.",
    },
    itinerary: [
      {
        day: 1,
        title: "Kathmandu to Pokhara",
        fromPlace: "Kathmandu",
        toPlace: "Pokhara",
        sleepAltitudeM: 822,
        accommodation: "hotel",
        meals: ["dinner"],
        isTravelDay: true,
      },
      {
        day: 2,
        title: "Fly to Jomsom, walk to Kagbeni",
        fromPlace: "Pokhara",
        toPlace: "Kagbeni",
        sleepAltitudeM: 2810,
        walkingHours: "3",
        distanceKm: 8,
        accommodation: "teahouse",
        meals: BLD,
        isTravelDay: true,
        note: "The restricted-area permit is checked at Kagbeni. It is itemised in full on the cost sheet.",
      },
      {
        day: 3,
        title: "Kagbeni to Chele",
        fromPlace: "Kagbeni",
        toPlace: "Chele",
        sleepAltitudeM: 3050,
        walkingHours: "6",
        distanceKm: 14,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 4,
        title: "Chele to Syangboche",
        fromPlace: "Chele",
        toPlace: "Syangboche",
        sleepAltitudeM: 3800,
        walkingHours: "7",
        distanceKm: 16,
        accommodation: "teahouse",
        meals: BLD,
        note: "Two passes above 3,700 m and the biggest gain of the trek.",
      },
      {
        day: 5,
        title: "Syangboche to Ghami",
        fromPlace: "Syangboche",
        toPlace: "Ghami",
        sleepAltitudeM: 3520,
        walkingHours: "5",
        distanceKm: 12,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 6,
        title: "Ghami to Tsarang",
        fromPlace: "Ghami",
        toPlace: "Tsarang",
        sleepAltitudeM: 3560,
        walkingHours: "5",
        distanceKm: 13,
        accommodation: "teahouse",
        meals: BLD,
        note: "Past the longest mani wall in Mustang.",
      },
      {
        day: 7,
        title: "Tsarang to Lo Manthang",
        fromPlace: "Tsarang",
        toPlace: "Lo Manthang",
        sleepAltitudeM: 3840,
        walkingHours: "5",
        distanceKm: 14,
        accommodation: "lodge",
        meals: BLD,
      },
      {
        day: 8,
        title: "Lo Manthang rest day",
        toPlace: "Lo Manthang",
        sleepAltitudeM: 3840,
        walkingHours: "3",
        accommodation: "lodge",
        meals: BLD,
        isAcclimatisation: true,
        note: "The walled town, the three gompas and the cave monasteries at Chhoser. No net gain and a short day.",
      },
      {
        day: 9,
        title: "Lo Manthang to Dhakmar",
        fromPlace: "Lo Manthang",
        toPlace: "Dhakmar",
        sleepAltitudeM: 3820,
        walkingHours: "6",
        distanceKm: 17,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 10,
        title: "Dhakmar to Syangboche",
        fromPlace: "Dhakmar",
        toPlace: "Syangboche",
        sleepAltitudeM: 3800,
        walkingHours: "6",
        distanceKm: 15,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 11,
        title: "Syangboche to Chuksang",
        fromPlace: "Syangboche",
        toPlace: "Chuksang",
        sleepAltitudeM: 3050,
        walkingHours: "6",
        distanceKm: 16,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 12,
        title: "Chuksang to Jomsom",
        fromPlace: "Chuksang",
        toPlace: "Jomsom",
        sleepAltitudeM: 2720,
        walkingHours: "5",
        distanceKm: 15,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 13,
        title: "Fly to Pokhara, on to Kathmandu",
        fromPlace: "Jomsom",
        toPlace: "Kathmandu",
        sleepAltitudeM: 1400,
        accommodation: "hotel",
        meals: ["breakfast"],
        isTravelDay: true,
        note: "The Jomsom flight goes early or not at all. If it is cancelled we drive, and the difference is ours.",
      },
    ],
  },

  "poon-hill": {
    trekName: "Ghorepani and Poon Hill",
    region: "Annapurna",
    difficulty: "moderate",
    maxAltitudeM: 3210,
    guideRatio: "1:6",
    groupSizeMax: 12,
    summary:
      "Five days on the Ghorepani ridge, with the Poon Hill viewpoint at 3,210 m reached at dawn on day four. The highest night is 2,874 m, which puts the whole route below the altitude at which most people feel anything.",
    physicalDemand: {
      walkingHoursPerDay: "4–6",
      consecutiveDays: 3,
      terrain:
        "Stone staircases through rhododendron forest — the Ulleri steps alone are around 3,300 of them — then an open ridge.",
      preparationNote:
        "Three walking days of four to six hours, almost all of it on steps. Stair climbing rather than distance is what this route asks for.",
    },
    itinerary: [
      {
        day: 1,
        title: "Kathmandu to Pokhara",
        fromPlace: "Kathmandu",
        toPlace: "Pokhara",
        sleepAltitudeM: 822,
        accommodation: "hotel",
        meals: ["dinner"],
        isTravelDay: true,
      },
      {
        day: 2,
        title: "Pokhara to Ulleri",
        fromPlace: "Pokhara",
        toPlace: "Ulleri",
        sleepAltitudeM: 2070,
        walkingHours: "4",
        distanceKm: 8,
        accommodation: "teahouse",
        meals: BLD,
        note: "Drive to Nayapul, then the Ulleri staircase. It is the hardest hour of the trek and it comes early.",
      },
      {
        day: 3,
        title: "Ulleri to Ghorepani",
        fromPlace: "Ulleri",
        toPlace: "Ghorepani",
        sleepAltitudeM: 2874,
        walkingHours: "5",
        distanceKm: 10,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 4,
        title: "Poon Hill at dawn, then Tadapani",
        fromPlace: "Ghorepani",
        toPlace: "Tadapani",
        sleepAltitudeM: 2630,
        maxAltitudeM: 3210,
        walkingHours: "6",
        distanceKm: 12,
        accommodation: "teahouse",
        meals: BLD,
        note: "A 04:45 start for the viewpoint, back for breakfast, then across to Tadapani.",
      },
      {
        day: 5,
        title: "Tadapani to Pokhara",
        fromPlace: "Tadapani",
        toPlace: "Pokhara",
        sleepAltitudeM: 822,
        walkingHours: "4",
        accommodation: "hotel",
        meals: ["breakfast", "lunch"],
        isTravelDay: true,
      },
    ],
  },

  "mardi-himal": {
    trekName: "Mardi Himal",
    region: "Annapurna",
    difficulty: "moderate",
    maxAltitudeM: 4500,
    guideRatio: "1:6",
    groupSizeMax: 10,
    summary:
      "Seven days on the ridge below Machhapuchhre, reaching the Mardi Himal viewpoint at 4,500 m and sleeping no higher than 3,580 m. The route only opened to teahouse trekking in 2012, so the lodges are small and the trail is quieter than the Annapurna sanctuary.",
    physicalDemand: {
      walkingHoursPerDay: "4–7",
      consecutiveDays: 5,
      terrain:
        "Forest ridge, then a narrow open crest above the treeline. The viewpoint day is a 900 m climb and a 900 m descent on the same ground.",
      preparationNote:
        "Five walking days, with one that gains and gives back 900 m between breakfast and dinner. Sustained uphill on a narrow path is the thing to be ready for.",
    },
    itinerary: [
      {
        day: 1,
        title: "Kathmandu to Pokhara",
        fromPlace: "Kathmandu",
        toPlace: "Pokhara",
        sleepAltitudeM: 822,
        accommodation: "hotel",
        meals: ["dinner"],
        isTravelDay: true,
      },
      {
        day: 2,
        title: "Pokhara to Forest Camp",
        fromPlace: "Pokhara",
        toPlace: "Forest Camp",
        sleepAltitudeM: 2600,
        walkingHours: "5",
        distanceKm: 11,
        accommodation: "teahouse",
        meals: BLD,
        note: "Drive to Kande, then a long climb through rhododendron and oak.",
      },
      {
        day: 3,
        title: "Forest Camp to Low Camp",
        fromPlace: "Forest Camp",
        toPlace: "Low Camp",
        sleepAltitudeM: 2970,
        walkingHours: "4",
        distanceKm: 6,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 4,
        title: "Low Camp to High Camp",
        fromPlace: "Low Camp",
        toPlace: "High Camp",
        sleepAltitudeM: 3580,
        walkingHours: "4",
        distanceKm: 6,
        accommodation: "teahouse",
        meals: BLD,
        note: "The treeline is crossed on this day and the ridge opens out on both sides.",
      },
      {
        day: 5,
        title: "Mardi Himal viewpoint and back",
        toPlace: "High Camp",
        sleepAltitudeM: 3580,
        maxAltitudeM: 4500,
        walkingHours: "7",
        accommodation: "teahouse",
        meals: BLD,
        note: "Up the ridge to 4,500 m and back down to the same bed. The trek's high point is reached and given up inside one day.",
      },
      {
        day: 6,
        title: "High Camp to Siding",
        fromPlace: "High Camp",
        toPlace: "Siding",
        sleepAltitudeM: 1750,
        walkingHours: "6",
        distanceKm: 14,
        accommodation: "teahouse",
        meals: BLD,
      },
      {
        day: 7,
        title: "Siding to Pokhara",
        fromPlace: "Siding",
        toPlace: "Pokhara",
        sleepAltitudeM: 822,
        walkingHours: "2",
        accommodation: "hotel",
        meals: ["breakfast", "lunch"],
        isTravelDay: true,
      },
    ],
  },

  "chitwan-safari": {
    trekName: "Chitwan River and Jungle",
    region: "Terai",
    difficulty: "moderate",
    maxAltitudeM: 415,
    guideRatio: "1:6",
    groupSizeMax: 10,
    summary:
      "Five days in Chitwan National Park on foot, by canoe and by jeep, with a licensed naturalist rather than a driver. Nothing on this itinerary goes above 415 m.",
    physicalDemand: {
      walkingHoursPerDay: "2–4",
      consecutiveDays: 3,
      terrain:
        "Flat sal forest, grassland and river bank. Warm and humid rather than steep; the demand is heat, not gradient.",
      preparationNote:
        "Two to four hours of flat walking a day, in temperatures that reach the low thirties. No altitude and no climbing at any point.",
    },
    itinerary: [
      {
        day: 1,
        title: "Kathmandu to Sauraha",
        fromPlace: "Kathmandu",
        toPlace: "Sauraha",
        sleepAltitudeM: 415,
        accommodation: "lodge",
        meals: ["dinner"],
        isTravelDay: true,
        note: "Six hours by road, or a 25-minute flight to Bharatpur at no extra cost.",
      },
      {
        day: 2,
        title: "Canoe on the Rapti, jungle walk",
        toPlace: "Sauraha",
        sleepAltitudeM: 415,
        walkingHours: "3",
        accommodation: "lodge",
        meals: BLD,
        note: "Dugout canoe at first light for gharial and marsh mugger, then a walk in the sal forest.",
      },
      {
        day: 3,
        title: "Full-day jeep safari",
        toPlace: "Sauraha",
        sleepAltitudeM: 415,
        walkingHours: "2",
        accommodation: "lodge",
        meals: BLD,
        note: "Deep into the park to the oxbow lakes. Rhino sightings are common; tiger sightings are not, and we will not tell you otherwise.",
      },
      {
        day: 4,
        title: "Tharu village and the elephant breeding centre",
        toPlace: "Sauraha",
        sleepAltitudeM: 415,
        walkingHours: "3",
        accommodation: "lodge",
        meals: BLD,
        note: "No elephant-back riding on any of our itineraries. The reason is on the safety page.",
      },
      {
        day: 5,
        title: "Sauraha to Kathmandu",
        fromPlace: "Sauraha",
        toPlace: "Kathmandu",
        sleepAltitudeM: 1400,
        accommodation: "hotel",
        meals: ["breakfast"],
        isTravelDay: true,
      },
    ],
  },

  "bardia-wildlife": {
    trekName: "Bardia National Park",
    region: "Terai",
    difficulty: "moderate",
    maxAltitudeM: 220,
    guideRatio: "1:5",
    groupSizeMax: 8,
    summary:
      "Six days in Bardia, the least visited of Nepal's large parks, tracking on foot with a naturalist and two park rangers. It is a twelve-hour drive or a one-hour flight from Kathmandu, which is why the crowds are elsewhere.",
    physicalDemand: {
      walkingHoursPerDay: "3–5",
      consecutiveDays: 4,
      terrain:
        "Flat riverine forest, grassland and the Karnali floodplain. Walking is slow and quiet rather than hard.",
      preparationNote:
        "Three to five hours a day on flat ground, often standing still for long stretches. Heat and patience are the demands; there is no altitude and no climbing.",
    },
    itinerary: [
      {
        day: 1,
        title: "Kathmandu to Thakurdwara",
        fromPlace: "Kathmandu",
        toPlace: "Thakurdwara",
        sleepAltitudeM: 220,
        accommodation: "lodge",
        meals: ["dinner"],
        isTravelDay: true,
        note: "Fly to Nepalgunj, then three hours by road to the park boundary.",
      },
      {
        day: 2,
        title: "Karnali floodplain on foot",
        toPlace: "Thakurdwara",
        sleepAltitudeM: 220,
        walkingHours: "5",
        accommodation: "lodge",
        meals: BLD,
        note: "On foot with a naturalist and two armed rangers, which is the park's own requirement and not an upsell.",
      },
      {
        day: 3,
        title: "Full-day jeep safari",
        toPlace: "Thakurdwara",
        sleepAltitudeM: 220,
        walkingHours: "3",
        accommodation: "lodge",
        meals: BLD,
      },
      {
        day: 4,
        title: "Dawn river watch, Tharu village",
        toPlace: "Thakurdwara",
        sleepAltitudeM: 220,
        walkingHours: "4",
        accommodation: "lodge",
        meals: BLD,
        note: "Gangetic dolphin are seen from the Karnali bank in the dry months. They are not seen every day.",
      },
      {
        day: 5,
        title: "Community forest and the buffer zone",
        toPlace: "Thakurdwara",
        sleepAltitudeM: 220,
        walkingHours: "4",
        accommodation: "lodge",
        meals: BLD,
      },
      {
        day: 6,
        title: "Thakurdwara to Kathmandu",
        fromPlace: "Thakurdwara",
        toPlace: "Kathmandu",
        sleepAltitudeM: 1400,
        accommodation: "hotel",
        meals: ["breakfast"],
        isTravelDay: true,
      },
    ],
  },

  "kathmandu-valley-rim": {
    trekName: "Kathmandu Valley Rim",
    region: "Kathmandu Valley",
    difficulty: "moderate",
    maxAltitudeM: 2175,
    guideRatio: "1:8",
    groupSizeMax: 14,
    summary:
      "Four days walking the ridge that encircles the Kathmandu valley, from Shivapuri down to Dhulikhel and out through Bhaktapur. The highest night is 2,175 m and no day carries a pack beyond a daypack.",
    physicalDemand: {
      walkingHoursPerDay: "4–6",
      consecutiveDays: 3,
      terrain:
        "Forest track, terraced farmland and village road. Undulating rather than steep, with one 700 m climb on the first day.",
      preparationNote:
        "Three walking days of four to six hours on well-made paths. Comfortable footwear matters more than training for this one.",
    },
    itinerary: [
      {
        day: 1,
        title: "Sundarijal to Chisapani",
        fromPlace: "Kathmandu",
        toPlace: "Chisapani",
        sleepAltitudeM: 2165,
        walkingHours: "5",
        distanceKm: 12,
        accommodation: "lodge",
        meals: BLD,
        isTravelDay: true,
        note: "Drive to the Sundarijal trailhead, then a climb through Shivapuri National Park.",
      },
      {
        day: 2,
        title: "Chisapani to Nagarkot",
        fromPlace: "Chisapani",
        toPlace: "Nagarkot",
        sleepAltitudeM: 2175,
        walkingHours: "6",
        distanceKm: 16,
        accommodation: "lodge",
        meals: BLD,
        note: "The long ridge day, with the Himalaya on the northern skyline whenever the haze lifts.",
      },
      {
        day: 3,
        title: "Nagarkot to Dhulikhel",
        fromPlace: "Nagarkot",
        toPlace: "Dhulikhel",
        sleepAltitudeM: 1550,
        walkingHours: "5",
        distanceKm: 14,
        accommodation: "hotel",
        meals: BLD,
      },
      {
        day: 4,
        title: "Dhulikhel to Bhaktapur and Kathmandu",
        fromPlace: "Dhulikhel",
        toPlace: "Kathmandu",
        sleepAltitudeM: 1400,
        walkingHours: "3",
        accommodation: "hotel",
        meals: ["breakfast", "lunch"],
        isTravelDay: true,
        note: "A morning in Bhaktapur Durbar Square on the way back in.",
      },
    ],
  },
};
