/**
 * Generates docs/IMAGE-SPEC.md from the slot registry.
 *
 *     pnpm docs:images          # write it
 *     pnpm docs:images --check   # fail if it is out of date
 *
 * The document is what somebody uploading a photograph reads, and the registry
 * is what the site actually renders with. Keeping them as two hand-maintained
 * things guarantees they disagree within a month — and a spec that disagrees
 * with the code is worse than none, because people follow it.
 *
 * So the document is output, not input. The `--check` mode runs in the build:
 * change a slot without regenerating and the build stops.
 */

import { readFile, readdir, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

import {
  IMAGE_SLOTS,
  UPLOAD_RULES,
  type ImageSlot,
} from "../src/lib/image-slots.ts";

const root = process.cwd();
const OUT = path.join(root, "docs", "IMAGE-SPEC.md");

/** Height at the ideal width, for slots with a fixed shape. */
function idealSize(slot: ImageSlot): string {
  if (!slot.aspect) return `${slot.idealWidth}px wide, any height`;
  return `${slot.idealWidth} × ${Math.round(slot.idealWidth / slot.aspect)} px`;
}

function minSize(slot: ImageSlot): string {
  if (!slot.aspect) return `${slot.minWidth}px wide`;
  return `${slot.minWidth} × ${Math.round(slot.minWidth / slot.aspect)} px`;
}

const rows = Object.entries(IMAGE_SLOTS)
  .map(
    ([key, slot]) =>
      `| **${slot.label}** | ${slot.aspectLabel} | ${minSize(slot)} | ${idealSize(slot)} | \`${key}\` |`,
  )
  .join("\n");

const detail = Object.entries(IMAGE_SLOTS)
  .map(([key, slot]) => {
    const lines = [
      `### ${slot.label}`,
      "",
      slot.purpose,
      "",
      `- **Shape** — ${slot.aspectLabel}`,
      `- **Minimum upload** — ${minSize(slot)}`,
      `- **Upload this** — ${idealSize(slot)}`,
      `- **Focal point** — defaults to ${slot.focal.replace("-", " ")}`,
      `- **Slot name in code** — \`${key}\``,
    ];
    if (slot.note) lines.push("", `> ${slot.note}`);
    return lines.join("\n");
  })
  .join("\n\n");

const doc = `# Image specification

**Generated from \`src/lib/image-slots.ts\`. Do not edit this file — edit the
registry and run \`pnpm docs:images\`.**

This is what to upload, and what the site does with it.

## The short version

Upload the biggest, uncropped version you have. The site handles the rest: it
crops each photograph for every place it appears, generates the smaller sizes,
converts the format, and holds on to the subject rather than the middle of the
frame when something has to be cut. You do not need to prepare a different file
per section, and you should not try to.

## Sizes at a glance

| Where it appears | Shape it renders at | Minimum | Upload this | Slot |
| --- | --- | --- | --- | --- |
${rows}

Every figure is a **minimum**, not a target. The site never upscales — a file
below the minimum is soft on a retina screen, and softness reads as cheapness
rather than as a mistake.

## Rules that apply to every upload

${UPLOAD_RULES.map((rule) => `**${rule.title}.** ${rule.body}`).join("\n\n")}

## Each slot in detail

${detail}

## How the automatic fitting works

Every photograph on the site is rendered through one component,
\`<SiteImage slot="…">\`, which reads the registry above. That means:

- **Cropped, never squashed.** Images fill their box with \`object-cover\`, so
  the shape of the box never distorts the picture.
- **The crop keeps the subject.** The focal point sets \`object-position\`, and
  the default sits slightly above centre because that is where subjects are —
  a centred crop of a person keeps the chin and loses the head.
- **The space is reserved before the file arrives.** The aspect ratio is applied
  by the wrapper, so nothing on the page moves as images load.
- **The browser downloads a file sized for the box.** Each slot carries its own
  \`sizes\`, so a 96px thumbnail fetches a 96px file and a full-bleed header
  fetches a wide one, from the same upload.

### If a photograph is the wrong shape for a slot

It still works, and here is exactly what happens. A tall photograph in a wide
slot keeps a horizontal band through the focal point and loses the top and
bottom. A wide photograph in a tall slot keeps a vertical band and loses the
sides. Nothing is stretched and nothing is letterboxed, except in the full-size
gallery view, which is the one place the whole frame is shown.

If a particular photograph crops badly, set its focal point rather than
re-cropping the file. That fixes it in every slot at once.

## When the admin upload screen is built

The registry is the contract. An upload form should:

1. Reject anything narrower than the smallest \`minWidth\` above, with the
   figure in the message rather than a generic "too small".
2. Convert HEIC and strip non-sRGB colour profiles on the way in.
3. Offer a focal-point picker — a click on the image — and store the result
   alongside the file. It is one field and it removes most cropping complaints.
4. Store the original. Every derivative on the site is generated from it, so a
   later redesign that needs a bigger or differently-shaped version does not
   need the photographs taken again.
5. Strip GPS coordinates from EXIF. Photographs of a guide's home village
   should not publish its location.
`;

const wanted = doc.trimStart();

/* ------------------------------------------------- nothing bypasses the system */

/*
 * `next/image` used directly means a photograph rendered with a hand-written
 * `sizes` and no focal point — which is how a site ends up serving a 3,000px
 * file into a 96px thumbnail on one page and cropping a guide's head off on
 * another. Every photograph goes through `<SiteImage>` so the numbers come from
 * one registry and an unedited upload lands correctly wherever it appears.
 *
 * Two files are allowed to import it directly and both have a reason written
 * above the import: `site-image.tsx` is the wrapper, and `hero-media.tsx`
 * carries a blur placeholder, a per-slide filter and its own focal point, which
 * the shared component would have to grow three props to support and use
 * nowhere else. It still reads its `sizes` and `quality` from the registry.
 */
const DIRECT_IMAGE_ALLOWED = new Set([
  "src/components/site-image.tsx",
  "src/components/hero/hero-media.tsx",
]);

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const found: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await walk(full)));
    else found.push(full);
  }
  return found;
}

const problems: string[] = [];
const sourceFiles = (await walk(path.join(root, "src"))).filter((f) =>
  f.endsWith(".tsx"),
);

for (const file of sourceFiles) {
  const rel = path.relative(root, file).replace(/\\/g, "/");
  const source = await readFile(file, "utf8");

  if (/from "next\/image"/.test(source) && !DIRECT_IMAGE_ALLOWED.has(rel)) {
    problems.push(
      `${rel} imports next/image directly — render it through <SiteImage slot="..."> so it picks up the registry's sizes, quality and focal point`,
    );
  }

  // A hand-written `sizes` is the same fault wearing a different hat.
  if (/\bsizes="/.test(source) && !DIRECT_IMAGE_ALLOWED.has(rel)) {
    problems.push(
      `${rel} sets sizes by hand — that belongs in src/lib/image-slots.ts`,
    );
  }
}

/* Every slot has to be plausible on its own terms. */
for (const [key, slot] of Object.entries(IMAGE_SLOTS)) {
  if (slot.idealWidth < slot.minWidth) {
    problems.push(`${key}: idealWidth is below minWidth`);
  }
  if (slot.minWidth < 200)
    problems.push(
      `${key}: minWidth ${slot.minWidth} is too small to be a real minimum`,
    );
  if (slot.quality < 30 || slot.quality > 90) {
    problems.push(`${key}: quality ${slot.quality} is outside 30-90`);
  }
  if (!slot.purpose.trim() || !slot.aspectLabel.trim()) {
    problems.push(`${key}: has no purpose or shape description for the spec`);
  }
}

if (problems.length) {
  console.log("\n  Image spec\n\n  Problems:");
  for (const problem of problems) console.log(`    ${problem}`);
  console.log("");
  process.exit(1);
}

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = await readFile(OUT, "utf8");
  } catch {
    current = "";
  }
  if (current.trim() !== wanted.trim()) {
    console.error(
      "\n  docs/IMAGE-SPEC.md is out of date with src/lib/image-slots.ts." +
        "\n  Run: pnpm docs:images\n",
    );
    process.exit(1);
  }
  console.log(
    `\n  Image spec\n\n  ok    ${Object.keys(IMAGE_SLOTS).length} slots documented, spec matches the registry\n`,
  );
} else {
  await mkdir(path.dirname(OUT), { recursive: true });
  await writeFile(OUT, wanted, "utf8");
  console.log(
    `\n  Wrote docs/IMAGE-SPEC.md — ${Object.keys(IMAGE_SLOTS).length} slots\n`,
  );
}
